### ISSUE TITLE
rdflib 6.1.0 and 6.1.1 fail unit tests

### ISSUE THREAD

**Issue by hsolbrig** [Harold-Solbrig/funowl#34]
It turns out that the 6.1 release of rdflib makes a mess of the prefix bindings.  A graph now comes "out of the box" with 40+ prefixes.

**Comment by cmungall** [comment]
This is the rdflib issue: https://github.com/RDFLib/rdflib/issues/1679

**Comment by hsolbrig** [comment]
This issue has been fixed by the inclusion of rdflib-shim and the somewhat redundant change to the pipenv.   OK to close or should we let it sit until the issue above is reconciled one way or the other?

**Comment by cmungall** [comment]
the rdflib folks have still to make a new release

meanwhile it's impossible to combine sparqlwrapper and funowl:

https://github.com/RDFLib/sparqlwrapper/issues/219

**Comment by cmungall** [comment]
@hsolbrig it looks like you added something to skip tests if the rdflib version is 6.1.1, since this is the version that pollutes namespaces. However, it looks like versions from 6.3 onwards regress to polluting namespaces, so I will modify this test to skip these versions too
